version: '3.7'
services:
    # Database
    toptal-database:
      container_name: toptal
      image: mcr.microsoft.com/mssql/server:2017-latest
      hostname: toptal
      ports:
        - 1433:1433
      environment:
        SA_PASSWORD: "YourStrong@Passw0rd"
        ACCEPT_EULA: "Y"
        MSSQL_AGENT_ENABLED: "True"
        #MSSQL_AGENT_ENABLED: "Y"
      networks:
        - toptal-project-compose-network

    redis:
        image: 'redis:5.0.5'
        # command: redis-server --requirepass redispass
        networks:
            - toptal-project-compose-network

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # Uncomment these lines to persist data on the local filesystem.
        #     - PGDATA=/var/lib/postgresql/data/pgdata
        # volumes:
        #     - ./pgdata:/var/lib/postgresql/data/pgdata
        networks:
            - toptal-project-compose-network

    webserver:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./csv:/usr/local/airflow/csv
            - ./sql:/usr/local/airflow/sql
            - ./json_etl:/usr/local/airflow/json_etl
            - ./json_setup:/usr/local/airflow/json_setup
            #- ./logs:/usr/local/airflow/logs
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        networks:
            - toptal-project-compose-network

    flower:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower
        networks:
            - toptal-project-compose-network

    scheduler:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./csv:/usr/local/airflow/csv
            - ./sql:/usr/local/airflow/sql
            - ./json_etl:/usr/local/airflow/json_etl
            - ./json_setup:/usr/local/airflow/json_setup
            #- ./logs:/usr/local/airflow/logs
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler
        networks:
            - toptal-project-compose-network

    worker:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./csv:/usr/local/airflow/csv
            - ./sql:/usr/local/airflow/sql
            - ./json_etl:/usr/local/airflow/json_etl
            - ./json_setup:/usr/local/airflow/json_setup
            #- ./logs:/usr/local/airflow/logs
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker
        networks:
            - toptal-project-compose-network

networks: 
  toptal-project-compose-network:
    driver: bridge